import employee
import company
import logging

print("Hello DataLovers Igor Semenduev")
logging.basicConfig(level=logging.DEBUG, filename='myapp.log',
                    format='%(asctime)s %(levelname)s:%(message)s')
logging.info('DataLovers start')
empl = employee.Employee(2222, 'Moshe', 'Cohen', 5000, 'Hadera')
print(empl)
empl.raise_salary(10)
print(empl.__dict__())
contra_empl = employee.Conractor(2587, 'Israela', 'Levi', 3200, 'Tira', 'Hura')
print(contra_empl)
print(contra_empl.__dict__())
comp_empl = employee.CompanyEmployee(1212, 'Haim', 'Bublil', 1800, 'Dimona')
print(comp_empl)
print(comp_empl.__dict__())
comp_empl.decrease_daysoff(3)
print(comp_empl.__dict__())

comp = company.Company('DataLovers')
print(comp)
comp.add_employee(contra_empl)
print(comp)
comp.add_employee(comp_empl)
print(comp)
avg_salary = comp.avg_salary()
print(f'Average salary is {avg_salary}')
avg_contractor_salary = comp.contractor_avg_salary()
print(f'Average contractor salary is {avg_contractor_salary}')
comp.remove_employee(1212)
print(comp)
comp.add_employee(empl)
print(comp)
comp = company.Company('DataLovers')
comp.load_employees('employees.json')
print(comp)
comp.update_employees('update_employees.json')
comp = company.Company('DataLovers')
comp.load_employees('update_employees.json')
print(comp)
comp = company.Company('DataLovers')
comp.load_employees('employees.json')

